### ISSUE TITLE
RuntimeError: Checksum mismatch after transfer

### ISSUE THREAD

**Issue by alfrenovsky** [vog/bscp#10]
I dont know if the syntax is right.
I'm using: 

` ./bscp  /dev/sda2 10.32.0.255:/dev/sda2`

And I get:

```
Traceback (most recent call last):
  File "./bscp", line 162, in <module>
    (in_total, out_total, size) = bscp(local_filename, remote_host, remote_filename, blocksize, hashname)
  File "./bscp", line 142, in bscp
    raise RuntimeError('Checksum mismatch after transfer')
RuntimeError: Checksum mismatch after transfer
```

No other output before that.
I have python 2.7.15rc1 in Ubuntu 18.

**Comment by vog** [comment]
This is strange.

The error message means that all blocks had correct checksums, but the overall checksum did not match.

To debug this, please try to do the same with files rather than devices. Also, you might want to use smaller files (i.e. tens of megabytes rather than gigabytes).

**Comment by marcin-github** [comment]
The same here. Both devices have different checksum after running bscp, devices are unmounted.# \# python2 -V
Python 2.7.15

Gentoo

**Comment by marcin-github** [comment]
I can see possible problem in invoking python on remote side. Default version of python is 3.x but changing bscp in this way:
```
-        remote_command = 'python -c "%s"' % (remote_script,)
+        remote_command = 'python2 -d -c "%s"' % (remote_script,)
``` didn't solve problem. How to catch output from snippet running on remote side?

**Comment by vog** [comment]
Both sides communicate over a binary protocol. Mostly transferring raw data (from the block devices), also exchanging size and checksum information in between. Essentially, you can intercept any ".read()" and ".write()" and print the received value (size, checksum, raw data) to the console.

**Comment by vog** [comment]
@xtaran Thanks for your thorough analysis! I fully agree with it and accepted the pull request.

**Comment by vog** [comment]
To anyone involved in this issue, please see #16 "Future of bscp".
