### ISSUE TITLE
Destination bigger than source

### ISSUE THREAD

**Issue by introlinux** [vog/bscp#4]
Hi Volker, I used in the pass blocksync.py for these tasks, but it imposes a mandatory condition: source must be identical in size to the target. I was looking for an alternative an I found your utility in github and after test it I saw that it is possible to copy with a bigger destination device, but I don't know if it is safe because I did not see anything on the web about it.

**Comment by vog** [comment]
Yes, this is possible, thanks to the contribution by @art0int in #1. I just improved the documentation website accordingly.

**Comment by vog** [comment]
To anyone involved in this issue, please see #16 "Future of bscp".
