### ISSUE TITLE
Poll: Use stronger hash algorithm by default?

### ISSUE THREAD

**Issue by vog** [vog/bscp#6]
@art0int @geaplanet @introlinux @rtmf

Bscp uses SHA-1 by default, which is no longer considered a strong crypto hash. Should we switch to SHA-256 by default?

Or, are you already using SHA-256 (or stronger) via the "HASH" command line option anyway?

Please share your opinions!

**Comment by introlinux** [comment]
In my environment crypto options are not very important, I always use bscp with default options.

**Comment by vog** [comment]
@introlinux Thanks for stepping up. Would you mind trying bscp with another hash setting (e.g. `sha256`) and compare the performance with `sha1`, in your specific setup?

Also, what's about the others? Which hash do you use? More opinions?

(To explain my questions: Although I wrote `bscp`, I don't actively use it anymore, because I use a different backup setup. So I need the input of real users - you - to make proper decisions.)

**Comment by vog** [comment]
Thanks to all for the feedback. I'm closing this issue, as I didn't receive any interest in changing the default value.

**Comment by vog** [comment]
To anyone involved in this issue, please see #16 "Future of bscp".
